### ISSUE TITLE
Rounded Square Root of 2

### ISSUE THREAD

**Issue by wsdev-co** [tovicheung/SquareRoot2Py#2]
How can we round the result? Can you please publish another package for this, such as `**RoundedSquareRoot2Py**`?

**Comment by tovicheung** [comment]
Maintaining two packages can be hard and require a lot of effort, but simply adding a new function may confuse users as not all of them wants the rounded value. Also, it might cause the main `SquareRoot2Py` module to load slower, affecting users that don't even need the extra feature.

To have the best of both worlds, the submodule `SquareRoot2Py.RoundedSquareRoot2Py` is created to address this serious issue.

**Comment by wsdev-co** [comment]
I admire the effort you put into this. I deployed your code, man, that is eloquently optimized.
Also, would be great to see SquareRoot2PyWithAdjustableRounding.py in order accurately calculate the U.S. Government Budget.
